### PR TITLE
add probot/stale functionality

### PR DESCRIPTION
**Pull request by samandmoore**
setup the probot stale helper so that stale issues and PRs will be bumped and cleaned up automatically. https://github.com/probot/stale

/domain @Betterment/webvalve-core @chrislopresto
/no-platform

### CODE REVIEW

**Comment by smudge** [comment]
Seems pretty nifty -- is there a story for keeping track of backlog issues / feature wishlists somewhere? Just mark them as `pinned`?

**Comment by samandmoore** [comment]
> Seems pretty nifty -- is there a story for keeping track of backlog issues / feature wishlists somewhere? Just mark them as `pinned`?

yea, basically. we can customize this config to ignore things that are part of a github project as well. then we could create a "backlog" project. or we can use another label and also ignore those, e.g. "backlogged"

**Comment by smudge** [comment]
SGTM - we can fine tune things as we go. As-is it'll probably close out the issues you've created.

<< domain LGTM

**Comment by samandmoore** [comment]
i just pinned 'em

**Comment by samandmoore** [comment]
but either way, it would label them stale first. then wait 7 days to close them.

**Comment by chrislopresto** [comment]
Nice.

**Pull request merged**
