### PR TITLE
Allow optional whitelist_in_spec for URLs

### PR DESCRIPTION
**Pull request by H-KE**
It would be nice to allow whitelisted urls to persist in the test env.

Helpful when testing against a remote selenium server or against a real endpoint (otherwise, WebValve prevents that from happening save for a janky monkey patch).

Proposed code extends `whitelist_url` functionality through a config class that takes in optional parameters in a similar pattern to how `FakeServiceConfig` is built.

This change is backwards compatible to existing configurations.

### CODE REVIEW

**Comment by samandmoore** [comment]
@H-KE sorry for the delay, i wasn't around last week. i will try to dig in this week.

**Comment by H-KE** [comment]
bump

**Comment by samandmoore** [comment]
@H-KE so i just dug through this. Can you talk to me more about your use-case for this change?

I see that you said this:
> Helpful when testing against a remote selenium server or against a real endpoint (otherwise, WebValve prevents that from happening save for a janky monkey patch).

But, I don't fully understand. Do you want _some_ of the requests to be routed into webvalve and _others_ to be routed for real? 

And, in which environment do you need that behavior?

Thanks!

**Comment by samandmoore** [comment]
<<domain platform tafn

**Comment by H-KE** [comment]
Ah! The use case is to whitelist these requests in the `test` environment

**Comment by H-KE** [comment]
More specifically, the desire is to circumvent this statement:
https://github.com/Betterment/webvalve/blob/master/lib/webvalve/manager.rb#L53

A question to ask is: is there away to configure `WebMock` allowances that would override the configuration provided by `WebValve` here? Perhaps elsewhere in my initialization sequence?

If not, then I am hoping to configure `WebMock` whitelists through `WebValve` in the `test` environment so that the test can route _specified_ routes for real.

One use case is to set up remote selenium servers that are running IE drivers which my testing environment can connect to; in order to run feature specs and ensure basic support for early IE environments.

**Comment by samandmoore** [comment]
ah gotcha gotcha. so, you basically want specific test cases to be able to circumvent webvalve entirely? 

my concern with the solution here is that we'd be making it possible for someone to have mixed behavior in a single spec. i.e. their spec can hit one service for real but hits a fake for another. a sort of partially integrated spec. i don't have great words to describe why i'm apprehensive about that, but it feels like it could be confusing and a little bit of a foot-gun. 

> A question to ask is: is there a way to configure WebMock allowances that would override the configuration provided by WebValve here? Perhaps elsewhere in my initialization sequence? (I couldn't figure one out, which led me to doing this in webvalve)

i believe it's possible to use `WebMock.allow_net_connect!` in a `before` hook or `around` hook to allow certain specs to hit the internet if you're looking for an "internet on/off switch" kinda thing. That will circumvent WebValve entirely for that spec.

**Comment by H-KE** [comment]
I'll give that a shot, thanks @samandmoore!

**Comment by samandmoore** [comment]
Cool! I’m gonna leave this open. I don’t have the best understanding of how
selenium fits into the ruby process and test suite execution. The right
solution here might also be to make special exceptions for
selenium-test-execution modes; I just don’t wanna change the library until
I have a better understanding of how things work with remote selenium
setups. I’d be happy to get on a video chat or slack chat to discuss this
in more detail.

**Pull request closed without merging**
