### PR TITLE
fix: appraisals are out of date for sinatra upgrade

### PR DESCRIPTION
**Pull request by samandmoore**
cc @aburgel 

this was failing until i rebased on your fixes from #82 

/no-platform

### CODE REVIEW

**Comment by samandmoore** [comment]
oh fun, ruby version x gem version sadness. looking at it.

**Review by rzane — APPROVED** [review]
domain lgtm
platform lgtm

**Comment by samandmoore** [comment]
this branch is getting wrecked by some gem incompatibility between ruby < 3.2 and zeitwerk of a certain vintage. 

i have to figure out the right combination of gemfile settings + github actions matrix settings to get this humming. 

todo:
- [ ] drop ruby 3.0 (eol)
- [ ] drop ruby 3.1 (security maintainence)
- [ ] add ruby 3.3

^ this should make the zeitwerk thing moot

then we should also
- [ ] add rails 7.1
- [ ] add rails 8.0

**Comment by samandmoore** [comment]
also, my local system just hosed itself while i was working through this 😮‍💨

so i've gotta figure that out before i can actually get back to fixing this for realz.

**Review by rzane — APPROVED** [review]
domain lgtm

**Pull request merged**
